import { useState } from 'react';
import Modal from '../components/Modal'
import Button from '../components/Button';
function ModalPage(){
    const [showModal,setShowModal] = useState(false);
    const handleClick = ()=>{
       setShowModal(true);
    }
    const handleClose = ()=>{
        setShowModal(false)
    }
    const actionBar = <div>
        <Button primary onClick={handleClose}>I Accept</Button>
    </div>
    const modal = <Modal onClose = {handleClose} actionBar={actionBar}>
        <p>
            Here is an important agreement for you to accept
        </p>
    </Modal>
    return (
        <div className="relative">
            <Button primary rounded onClick={handleClick}>Open Modal</Button>
            {showModal && modal}
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc condimentum velit sed mauris posuere interdum. Nulla facilisi. Morbi scelerisque erat ut mattis efficitur. Nullam tortor lorem, hendrerit vel elementum eget, efficitur nec turpis. Phasellus vel ipsum id magna ultrices varius. Etiam laoreet, erat consequat auctor dictum, erat nisi aliquam lorem, nec lobortis felis orci at ligula. Nulla mollis, felis non euismod porta, magna mauris suscipit metus, scelerisque pretium urna ex sed ligula. Nullam et augue id lorem egestas aliquet. Nullam volutpat laoreet massa vel bibendum. In hac habitasse platea dictumst. Curabitur convallis ex sit amet leo rutrum, nec fringilla sem pretium. Nulla porttitor malesuada ultrices. Nulla vestibulum pretium metus, vitae convallis magna hendrerit eget. Ut libero dui, mollis a purus nec, commodo vehicula mauris. Nunc eu neque a ipsum porttitor porttitor. Donec nec libero vestibulum, finibus lectus a, tempus libero.</p>
        </div>
    )

}
export default ModalPage;